## Function for frequency calculation
frequency<- function(name,sdk){
    ## Packages used are mentioned below
    require(qdap)
    require(tm)
    #print(name)
    #print(sdk)
    sdk = tolower(sdk)
    sdk <- removePunctuation(sdk)
    keywords= switch (as.character(name),'Wal-Mart' = c('walmex','walmart')
                    ,'johnson' = c('johnson')
                    ,'3M' = c('3M','MMM')
                    ,'United Technologies' = c('United Technologies')
                    ,'Procter & Gamble'= c('Procter & Gamble','P&G','procter')
                    ,'Pfizer' = c('Pfizer')
                    ,'Verizon Communications'=c('Verizon Communications','verison')
                    ,'Microsoft' = c('microsoft','msft')
                    , 'Coca-Cola'=c('Coca-Cola')
                    , 'Merck'=c('Merck')
                    , 'Intel'=c('Intel')
                    , 'Travelers Companies'=c('Travelers Companies','travelers')
                    , 'Home Depot'=c('Home Depot')
                    , 'General Electric'=c('General Electric','GE')
                    , 'Boeing'=c('Boeing')
                    , 'American Express' = c('American Express','Amex')
                    , 'Goldman Sachs'=c('Goldman Sachs','gs')
                    , 'Nike'=c('Nike')
                    , 'Walt Disney' = c('Walt Disney','disney')
                    , 'Apple'=c('Apple','aapl')
                    , 'UnitedHealth' = c('UnitedHealth','UNH')
                    , 'Visa'=c('Visa')
                    , 'Cisco' = c('Cisco')
                    , 'International Business Machines' = c('International Business Machines','IBM')
                    , 'du Pont de Nemours' = c('du Pont de Nemours','DD','DuPont')
                    , 'Exxon Mobil'=c('Exxon Mobil','Exxon','Mobil')
                    , 'JP Morgan Chase'=c('JP Morgan Chase','JP','JPM')
                    , 'Chevron' = c('Chevron')
                    , 'Caterpillar' = c('Caterpillar',"CAT")
                    , 'McDonald'= c('McDonald','MCD'))
    
    p = sum(termco(text.var = sdk,match.list =keywords)$raw[3:(2+length(keywords))])
    return(p)
}